[book]
authors = ["Subhrajit"]
language = "en"
src = "src"
title = "Subhrajit"


[output.html]
default-theme = "macchiato"
preferred-dark-theme = "macchiato"
additional-css = [
  "src/css/extra.css",
  "./theme/catppuccin.css",
  "./theme/catppuccin-highlight.css",
]
git-repository-icon = "fa-github"
cname = "subhrajit.me"


[output.html.search]
limit-results = 15

[output.html.playground]
editable = false

[output.html.print]
enable = true     # include support for printable output
page-break = true # insert page-break after each chapter
